### ISSUE TITLE
After upgrade to 1.1.0, the module cannot be imported

### ISSUE THREAD

**Issue by gcampax** [ozra/mmap-io#17]
It looks like the current version of package.json no longer has a "main" field (it got lost in https://github.com/ozra/mmap-io/commit/29070c9065084e121c1522d8757677a262df5359), and that means that the package will fail to import:
```
> require('mmap-io')
{ Error: Cannot find module 'mmap-io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }
```

**Comment by erluko** [comment]
In addition to fixing the `main` field in package.json, I had to edit mmap-io.js since it refers to a nonexistent `es-release` directory. Changing this to `Release` allowed the import to succeed on my system.

**Comment by LiamKarlMitchell** [comment]
In package.json replace all "es-release" with "Release".
In nmap-io.js replace "es-release" with "Release".
In tsconfig.json replace "es-release" with "Release".
In package.json add "main": "mmap-io.js"

**Comment by ozra** [comment]
Sorry I didn't see the github notifications earlier, fixed and updated. Holler and tag me if you have any problems!

**Comment by gcampax** [comment]
Sorry, this is not fixed yet. The build artifact live in `build/Release` because you use node-gyp (as you should), but mmap-io.js imports `build/es-release/mmap-io`.
See an example of build failure: https://travis-ci.com/stanford-oval/genie-toolkit/builds/118448865 (from greenkeeper trying the new build on my project)

**Comment by gcampax** [comment]
(tagging @ozra as requested)

**Comment by ozra** [comment]
Alright, I'll go over it again, I'll dig up some of my old Quant-projects that use it heavily, and see how it behaves and get it right.

**Comment by ozra** [comment]
So... 
1. the es-release files where black-listed and therefor not packaged into the npm
2. when they got with, they where wiped out on installment when the binary was rebuilt
- turns out just getting rid of the Makefile caused more crap than I ever had imagined, this actually took longer to get straight than rewriting the horror-show V8-code [ed: _because they break compatibility every few months_ ] xD

Anyway, the js-files are now built into "dist" instead, and the binary into "build" as before, to keep them separated and thereby allow them to be built pre-publish and avoid unnecessary dependencies for the end-user, as intended.

Well. Should shit _still_ roar up — just tag and shout out. Your project seems really cool by the way! I've bookmarked it along with a trail of others I found from it. For "when there is time" xD

Cheers!
